"""Base-rate computations from the CAA panel: the project's first real numbers.

All outputs are computed on ARRIVAL rows only (EU261 turns on arrival delay at
final destination). Percent-band columns are per matched flight; cancellation
probability uses cancelled / (matched + cancelled).
"""

from __future__ import annotations

import logging
from pathlib import Path

import polars as pl

from wizarb.config import DATA_INTERIM, REPORTS, airline_group

log = logging.getLogger(__name__)

PANEL = DATA_INTERIM / "caa_punctuality.parquet"


def load_arrivals(panel_path: Path = PANEL) -> pl.DataFrame:
    df = pl.read_parquet(panel_path)
    df = df.filter(pl.col("arrival_departure") == "A")
    return df.with_columns(
        pl.col("airline_name")
        .map_elements(airline_group, return_dtype=pl.Utf8)
        .alias("carrier_group"),
        (pl.col("number_flights_matched") * pl.col("p_ge_3h")).alias("n_ge_3h"),
        (
            pl.col("number_flights_matched")
            * pl.col("average_delay_mins").fill_null(0)
        ).alias("delay_min_weighted"),
    )


def _rates(df: pl.DataFrame, keys: list[str]) -> pl.DataFrame:
    return (
        df.group_by(keys)
        .agg(
            pl.col("number_flights_matched").sum().alias("n_flights"),
            pl.col("number_flights_cancelled").sum().alias("n_cancelled"),
            pl.col("n_ge_3h").sum().alias("n_ge_3h"),
            pl.col("delay_min_weighted").sum().alias("delay_min_weighted"),
        )
        .with_columns(
            (pl.col("n_ge_3h") / pl.col("n_flights")).alias("p_ge_3h"),
            (
                pl.col("n_cancelled")
                / (pl.col("n_flights") + pl.col("n_cancelled"))
            ).alias("p_cancelled"),
            (pl.col("delay_min_weighted") / pl.col("n_flights")).alias("avg_delay_min"),
        )
        .drop("delay_min_weighted")
        .sort(["p_ge_3h"] + keys, descending=[True] + [False] * len(keys))
    )


def airline_table(df: pl.DataFrame, year: int, min_flights: int = 5_000) -> pl.DataFrame:
    t = _rates(df.filter(pl.col("year") == year), ["carrier_group"])
    return t.filter(pl.col("n_flights") >= min_flights)


def seasonality_table(df: pl.DataFrame, year: int, groups: list[str]) -> pl.DataFrame:
    t = _rates(
        df.filter(pl.col("year") == year, pl.col("carrier_group").is_in(groups)),
        ["carrier_group", "month"],
    )
    return t.sort(["carrier_group", "month"])


def route_table(
    df: pl.DataFrame,
    year: int,
    carrier_group: str | None = None,
    min_flights: int = 100,
    monthly: bool = False,
) -> pl.DataFrame:
    keys = ["carrier_group", "reporting_airport", "origin_destination"]
    if monthly:
        keys.append("month")
    sub = df.filter(pl.col("year") == year)
    if carrier_group:
        sub = sub.filter(pl.col("carrier_group") == carrier_group)
    return _rates(sub, keys).filter(pl.col("n_flights") >= min_flights)


def write_report(panel_path: Path = PANEL, out_dir: Path = REPORTS) -> Path:
    """Write CSV tables + a markdown summary of real computed base rates."""
    out_dir.mkdir(parents=True, exist_ok=True)
    df = load_arrivals(panel_path)
    years = sorted(df.get_column("year").unique().to_list())

    lines = [
        "# CAA base rates — computed from raw data",
        "",
        f"Arrival rows only. Years ingested: {years}.",
        "Generated by `wizarb base-rates`; tables in `reports/*.csv`.",
        "",
        "**Direction caveat:** CAA records delay at the *UK reporting airport*, so",
        "arrival rows are inbound legs (e.g. Bucharest→Luton). The outbound leg's",
        "EU261-relevant delay (arrival at the foreign destination) is only visible",
        "here as its UK *departure* delay — a proxy that overstates arrival delay by",
        "the ~5–15 min typically recovered in the air. Cell screening should be run",
        "both ways.",
        "",
    ]
    for year in years:
        at = airline_table(df, year)
        at.write_csv(out_dir / f"airline_p3h_{year}.csv")
        lines.append(f"## {year} — airline groups (min 5,000 arrivals)")
        lines.append("")
        lines.append("| Carrier | n arrivals | P(3h+) | P(cxl) | avg delay (min) |")
        lines.append("| --- | ---: | ---: | ---: | ---: |")
        for r in at.head(12).iter_rows(named=True):
            lines.append(
                f"| {r['carrier_group']} | {r['n_flights']:,} "
                f"| {r['p_ge_3h']:.2%} | {r['p_cancelled']:.2%} "
                f"| {r['avg_delay_min']:.1f} |"
            )
        lines.append("")

    # Route-level detail for the most recent complete year, worst cells first.
    last = years[-1]
    rt = route_table(df, last, min_flights=100)
    rt.write_csv(out_dir / f"routes_p3h_{last}.csv")
    rtm = route_table(df, last, min_flights=25, monthly=True)
    rtm.write_csv(out_dir / f"routes_p3h_monthly_{last}.csv")

    out = out_dir / "base-rates.md"
    out.write_text("\n".join(lines))
    log.info("wrote %s", out)
    return out
